style: {
  fill: transparent
  shadow: false
}

classes: {
  logic_app: {
    icon: ../icon/logic_apps.svg 
    shape: image
  }
  couchdb: {
    icon: ../icon/couchdb.svg 
    shape: image
  }
  github: {
    icon: ../icon/github.svg
    shape: image
  }
  devops: {
    icon: ../icon/devops.svg
    shape: image
  }
  vnet: {
    icon: ../icon/vnet.svg
    shape: image
  }
  sql: {
    icon: ../icon/sql.svg
    shape: image
  }
  mysql: {
    icon: ../icon/mysql.svg
    shape: image
  }
  cosmosdb: {
    icon: ../icon/cosmosdb.svg
    shape: image
  }
  nsg: {
    icon: ../icon/nsg.svg
    style: {
      stroke-dash: 8
      border-radius: 8
      stroke: deepskyblue
    }
  }
  netrule: {
    style: {
      stroke-dash: 8
      border-radius: 8
      stroke: deepskyblue
    }
  }
  vm: {
    icon: ../icon/vm.svg
    shape: image
  }
  organisation: {
    icon: ../icon/azure.svg 
    style.border-radius: 8
  }
  attacker_user {
    label: ''
    shape: circle
    style {
      border-radius: 8
      stroke: darkred
      fill: lightcoral
    }
  }
  attacker_user_icon {
    icon: ../icon/attacker.svg
    shape: image
    label: Attacker
  }
  successful_path: {
    style: {
      stroke: mediumseagreen
    }
  }
  attack_path: {
    style: {
      stroke: red
    }
  }
  failed_path: {
    style: {
      stroke: red
      stroke-dash: 5
      font-color: "#777777"
    }
    target-arrowhead {
      shape: none
    }
  }
}
